---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: check-docstring-first
  - id: check-added-large-files
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys]
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.1
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
  hooks:
  - id: reorder-python-imports
    args: [--py3-plus]
- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
  - id: docformatter
- repo: https://github.com/psf/black
  rev: 21.11b1
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear==21.9.2]
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-use-type-annotations
  - id: python-no-eval
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.1.0
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0']
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.10
  hooks:
  - id: mdformat
    name: Format Markdown files
