name: Check new tag

on:
  push:
    branches:
      - main
    paths:
      - 'setup.cfg'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get version
      id: version
      run: echo "::set-output name=version::$(awk -F '=' '/version/ {print $2}' setup.cfg | tr -d ' ')"
    - uses: mukunku/tag-exists-action@v1.0.0
      id: checkTag
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ steps.version.outputs.version }}
    - name: Tag new version
      if: ${{ steps.checkTag.outputs.exists != 'true' }}
      uses: tvdias/github-tagger@v0.0.2
      with:
        repo-token: ${{ secrets.TOKEN_PACKAGES }}
        tag: v${{ steps.version.outputs.version }}
