---
name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - docs/**
  pull_request:
    paths-ignore:
    - docs/**

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with:
        extra_args: --all-files

  tests:
    name: tests - Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    needs: pre-commit
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8', '3.9']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
    - name: Install package
      run: pip install -e .[test]
    - name: Run pytest
      run: pytest
    - name: Run build docker image
      run: |
        docker build -t iot-firmware --build-arg PYTHON_TAG=${{ matrix.python }}-slim .
        docker run iot-firmware -v
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        files: /home/runner/work/iot-firmware/iot-firmware/.coverage
        fail_ci_if_error: true
