name: Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install --upgrade setuptools build wheel
    - name: Build pip package
      run: python -m build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.whl
