name: Push pip package to release tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x64
    - name: Install dependencies
      run: pip install --upgrade -r requirements.txt setuptools build wheel
    - name: Build pip package
      run: python -m build .
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.whl
