name: Tests

on: push

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
        architecture: x64
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files

  unit:
    name: Unit Tests - Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    needs: pre-commit
    strategy:
      fail-fast: false
      matrix:
        python: [ '3.8', '3.9' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
    - name: Install package
      run: pip install .[test] --use-feature=in-tree-build
    - name: Run pytest
      run: pytest
